# Generated by Django 4.2.6 on 2023-11-01 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_alter_transactions_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('days', models.IntegerField(default=1)),
                ('food', models.CharField(max_length=20)),
                ('stay', models.CharField(max_length=20)),
                ('climate', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('transport', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cards',
            name='email',
            field=models.EmailField(default='group8@123', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 11, 1, 4, 35, 31, 268233, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
