# Generated by Django 4.2.6 on 2023-11-01 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_suggestion_alter_cards_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 11, 1, 4, 58, 17, 499254, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
